### ISSUE TITLE
[Jerome] Investigate Power.log corruption on upload

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#812] opened 2018-05-16 23:49 UTC
A small number of Power.log files seem to be getting HTTP headers prepended to them by HDT during upload, which makes it impossible to decode them as gzipped. I pulled one down using the AWS CLI (can't do it via the browser, since the object erroneously has "Content-Encoding: gzip" set on it) and found the following at the _beginning_ of the file:

```
PUT /raw/2018/05/16/03/15/[...].power.log?AWSAccessKeyId=[REDACTED]&Signature=[REDACTED]&content-type=text%2Fplain&x-amz-security-token=[REDACTED]&Expires=1526526950 HTTP/1.1
Content-Type: text/plain
Accept: application/json
User-Agent: HDT/1.6.5.3616
Host: hsreplaynet-uploads.s3.amazonaws.com
Content-Encoding: gzip
Content-Length: 28285
Expect: 100-continue
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
```
After this header, the gzipped bytes of the log follow.

This is reported in Sentry as "OSErrorhsreplaynet.uploads.models in log_bytes"  (https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/541286751/)

Created as part of #133.

**Comment by beheh** [comment] 2018-05-17 08:01
By itself I don't think this error is "wrong". As a followup, we should probably explicitely handle it though and mark the upload as an invalid replay. Furthermore, we can spend some time trying to root cause this in HDT itself, but who knows where this comes from - it could even be the behaviour of some buggy proxy server.

**Comment by amw2104** [comment] 2018-05-23 22:30
Since we have a different ticket to handle this and metric it, I am closing this since we cannot reproduce until it starts happening more frequently.

**Closed by amw2104** 2018-05-23 22:30 UTC
