### ISSUE TITLE
Stop creating partial decks in processing

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#367] opened 2017-07-06 19:05 UTC
Check that the deck size is 30, prevent its creation if it's not.

**Comment by beheh** [comment] 2017-07-06 19:06
What about `CHOOSE_ONE` entities?

**Comment by jleclanche** [comment] 2017-07-07 02:36
They're not in the deck...

**Comment by beheh** [comment] 2017-11-20 17:02
Duplicate of #296.

**Closed by beheh** 2017-11-20 17:02 UTC
