### ISSUE TITLE
Missing player name on replay page when unknown

### ISSUE THREAD

**Issue by Bert-Proesmans** [HearthSim/HSReplay.net#340] opened 2017-06-21 11:37 UTC
On the replay page under section 'players' the (opponent) player name is missing when it's unknown.
Clicking 'Show deck' in these cases also causes the decklist being misplaced and overlap the 'Hide deck' text. Trying to click on 'Hide deck' will actually result in navigating to the card page of the first displayed card (blood imp).

Screenshots
![deck list not shown](https://cdn.pbrd.co/images/2bfO7rw34.png)
![deck list shown](https://cdn.pbrd.co/images/dwC0rHcU.png)

**Comment by beheh** [comment] 2017-06-21 13:00
I think this is a duplicate of #101.

**Comment by jleclanche** [comment] 2017-06-22 20:09
It is.

**Closed by jleclanche** 2017-06-22 20:09 UTC
