### ISSUE TITLE
String encoding issue in find_or_create_replay

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#813] opened 2018-05-17 00:00 UTC
Upload processing intermittently fails in find_or_create_replay with the following error: `A string literal cannot contain NUL (0x00) characters.` ...which seems to come from SQLAlchemy.

Is it possible that some of the columns in game_replay aren't configured to hold UTF-8 strings? I notice the failures seem to be related to processing replays with text in non-European languages, e.g. Korean.

This is reported in Sentry as "ValueError hsreplaynet.games.processing in find_or_create_replay"  (https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/409237221/)

Created as part of #133.

**Comment by jleclanche** [comment] 2018-05-17 01:52
This is a dupe of HearthSim/hdt-internal#26. Closing.

**Closed by jleclanche** 2018-05-17 01:52 UTC
